#ifndef NRF51_BLE_DONGLE_CONFIG_H
#define NRF51_BLE_DONGLE_CONFIG_H

#define APP_IRQ_PRIORITY_LOWEST 3

#define APP_TIMER_CONFIG_OP_QUEUE_SIZE 4

#define APP_TIMER_CONFIG_RTC_FREQUENCY 0

#endif //NRF51_BLE_DONGLE_CONFIG_H
